name: ponto_eletronico
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.6.9
  firebase_core: ^3.14.0
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.0.15
  flutter_localizations:
    sdk: flutter
  intl: any

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_foreground: 'assets/icon/1024.png'
  adaptive_icon_background: "#F7F7F7"
  windows:
    generate: true
    image_path: "assets/icon/1024.png"
    icon_size: 48 # min:48, max:256, default: 48


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


